name: Run UnitTests
on:
  push:
    branches:
      - '*'

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install libgtest-dev cmake git libsodium-dev
      - name: Get sources
        run: git clone --depth=1 --no-single-branch https://github.com/Stephen-Seo/UDPConnection.git UDPC && cd UDPC && git checkout $GITHUB_REF_NAME
      - name: Build sources
        run: cd UDPC && cmake -S . -B buildDebug -DCMAKE_BUILD_TYPE=Debug && make -C buildDebug
      - name: Run tests
        run: ./UDPC/buildDebug/UnitTest
